# Mini-Project - Week 1

Now you will practice some of the skills you've learned from lab 1 and apply them in a short mini-project! We will be using a popular dataset called `gapminder` that contains information about different countries, their total population, life expectancy, gdp, and more by year from $1960$ to $2016$.

In [ ]:
# Import packages you may need
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
# Import gapminder data
url = "https://drive.google.com/file/d/1FisnRZ-X0r6Gltezy1OSeZzVJ9Q1HTFm/view?usp=sharing"
url_clean = 'https://drive.google.com/uc?id=' + url.split('/')[-2]
gapminder = pd.read_csv(url_clean)
gapminder.head()

,country,year,infant_mortality,life_expectancy,fertility,population,gdp,continent,region
0,Albania,1960,115.40,62.87,6.19,1636054.0,NaN,Europe,Southern Europe
1,Algeria,1960,148.20,47.50,7.65,11124892.0,1.382815e+10,Africa,Northern Africa
2,Angola,1960,208.00,35.98,7.32,5270844.0,NaN,Africa,Middle Africa
3,Antigua and Barbuda,1960,NaN,62.97,4.43,54681.0,NaN,Americas,Caribbean
4,Argentina,1960,59.87,65.39,3.11,20619075.0,1.083223e+11,Americas,South America

Conduct some exploratory data analysis (EDA) on the `gapminder` dataset. In particular, come up with _at least_ 2 different descriptive statistic outputs (i.e. a table or a plot) on different variables in the `gapminder` dataset and describe (in words) what kinds of things we might be able to infer about the data.

In [ ]:
# Your code here:

*Your written response here:*